fix Dockerfile cache
not doing this:

COPY go.mod go.sum go-ircevent
RUN --mount=type=cache,target=/go/pkg/mod go mod download
COPY . .
  ......

because I can't figure out how to make it not error

ERROR: failed to build: failed to solve: cannot copy to non-directory: /var/lib/docker/buildkit/containerd-overlayfs/cachemounts/buildkitxxxxxxxx/bot/.git